### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by quantumproducer** [ConsenSys/diligence-takehome#1]
Here's what happens:

sudo npm install

```

Password:
Unhandled rejection Error: Command failed: /usr/local/bin/git clone --depth=1 -q -b master https://github.com/debris/bignumber.js.git /Users/quantum/.npm/_cacache/tmp/git-clone-438f2df6
/Users/quantum/.npm/_cacache/tmp/git-clone-438f2df6/.git: Permission denied

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)

⸨            ░░░░░░⸩ ⠇ extract:npm: sill extract caller-path@0.1.0
```

Advice welcome. Including installation instructions on readme to confirm it works would be nice.

**Comment by quantumproducer** [comment]
Seemingly related: https://github.com/npm/npm/issues/17413
